# Generated by Django 5.1 on 2024-08-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Jurnal', 'jurnal'), ('Berita', 'berita'), ('Gosip', 'gosip')], default='jurnal', max_length=100)),
            ],
        ),
    ]
