# Generated by Django 5.1 on 2024-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_film_duration'),
        ('user', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='purchased_by', to='film.film'),
        ),
    ]
