# Generated by Django 5.1 on 2024-08-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
