# Generated by Django 5.1 on 2024-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=80)),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.JSONField(default=list)),
                ('price', models.IntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
