# Generated by Django 5.1 on 2024-08-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_alter_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to='static/media/videos/'),
        ),
    ]
