# Generated by Django 5.1 on 2024-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_alter_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
